apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
 app.kubernetes.io/part-of: wac-hospital
 app.kubernetes.io/name: mb-ambulance-wl

resources:
 - ../../../apps/mb-ambulance-ufe


components:
 - ../../../components/version-release